<?php

return [
    'guard' => 'web',

    'roles' => [
        'super_admin' => [
            'label' => 'Super Admin',
            'permissions' => ['*'],
        ],
        'admin' => [
            'label' => 'Admin',
            'permissions' => [
                'admin.dashboard.view',
                'users.view',
                'users.create',
                'users.update',
                'users.delete',
                'customers.view',
                'customers.update',
                'customers.notes.create',
                'customers.tags.update',
                'roles.view',
                'permissions.view',
                'settings.view',
                'settings.update',
                'modules.view',
                'modules.update',
                'categories.view',
                'categories.create',
                'categories.update',
                'categories.delete',
                'products.view',
                'products.create',
                'products.update',
                'products.delete',
                'products.publish',
                'inventory.view',
                'inventory.adjust',
                'inventory.reserve',
                'inventory.release',
                'orders.view',
                'orders.update_status',
                'orders.notes.create',
                'orders.cancel',
                'orders.returns.create',
                'orders.invoices.generate',
                'orders.packing_slips.generate',
                'orders.shipments.create',
                'shipping.view',
                'shipping.create',
                'shipping.update',
                'shipping.delete',
                'coupons.view',
                'coupons.create',
                'coupons.update',
                'coupons.delete',
                'payments.update',
                'payments.cod.collect',
                'reports.view',
            ],
        ],
        'manager' => [
            'label' => 'Manager',
            'permissions' => [
                'admin.dashboard.view',
                'users.view',
                'customers.view',
                'settings.view',
                'modules.view',
                'categories.view',
                'products.view',
                'inventory.view',
                'orders.view',
                'orders.notes.create',
                'orders.returns.create',
                'orders.invoices.generate',
                'orders.packing_slips.generate',
                'orders.shipments.create',
                'shipping.view',
                'coupons.view',
                'payments.update',
                'payments.cod.collect',
                'reports.view',
            ],
        ],
        'support' => [
            'label' => 'Support',
            'permissions' => [
                'admin.dashboard.view',
                'users.view',
                'customers.view',
                'customers.update',
                'customers.notes.create',
                'customers.tags.update',
                'inventory.view',
                'orders.view',
                'orders.update_status',
                'orders.notes.create',
                'orders.cancel',
                'orders.returns.create',
                'orders.invoices.generate',
                'orders.packing_slips.generate',
                'orders.shipments.create',
                'payments.update',
                'payments.cod.collect',
                'reports.view',
            ],
        ],
        'customer' => [
            'label' => 'Customer',
            'permissions' => [
                'customer.account.view',
                'customer.account.update',
            ],
        ],
    ],

    'permissions' => [
        'admin.dashboard.view' => 'View admin dashboard',
        'users.view' => 'View users',
        'users.create' => 'Create users',
        'users.update' => 'Update users',
        'users.delete' => 'Delete users',
        'customers.view' => 'View customers',
        'customers.update' => 'Update customer status',
        'customers.notes.create' => 'Create internal customer notes',
        'customers.tags.update' => 'Update customer tags',
        'roles.view' => 'View roles',
        'roles.create' => 'Create roles',
        'roles.update' => 'Update roles',
        'roles.delete' => 'Delete roles',
        'permissions.view' => 'View permissions',
        'permissions.create' => 'Create permissions',
        'permissions.update' => 'Update permissions',
        'permissions.delete' => 'Delete permissions',
        'settings.view' => 'View store settings',
        'settings.update' => 'Update store settings',
        'modules.view' => 'View module toggles',
        'modules.update' => 'Update module toggles',
        'categories.view' => 'View categories',
        'categories.create' => 'Create categories',
        'categories.update' => 'Update categories',
        'categories.delete' => 'Delete categories',
        'products.view' => 'View products',
        'products.create' => 'Create products',
        'products.update' => 'Update products',
        'products.delete' => 'Delete products',
        'products.publish' => 'Publish products',
        'inventory.view' => 'View inventory',
        'inventory.adjust' => 'Adjust inventory stock',
        'inventory.reserve' => 'Reserve inventory stock',
        'inventory.release' => 'Release inventory stock',
        'orders.view' => 'View orders',
        'orders.update_status' => 'Update order status',
        'orders.notes.create' => 'Create internal order notes',
        'orders.cancel' => 'Cancel orders',
        'orders.returns.create' => 'Create return requests',
        'orders.invoices.generate' => 'Generate order invoices',
        'orders.packing_slips.generate' => 'Generate packing slips',
        'orders.shipments.create' => 'Create order shipments',
        'shipping.view' => 'View shipping zones and rates',
        'shipping.create' => 'Create shipping zones and rates',
        'shipping.update' => 'Update shipping zones and rates',
        'shipping.delete' => 'Delete shipping zones and rates',
        'coupons.view' => 'View coupons',
        'coupons.create' => 'Create coupons',
        'coupons.update' => 'Update coupons',
        'coupons.delete' => 'Delete coupons',
        'payments.update' => 'Update payment status',
        'payments.cod.collect' => 'Collect COD payments',
        'reports.view' => 'View reports',
        'customer.account.view' => 'View customer account',
        'customer.account.update' => 'Update customer account',
    ],
];
